---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  
  tasks:
   - name: Create a VM
     vsphere_guest:
       vcenter_hostname: raspberrypi.home
       esxi:
         datacenter: ha-datacenter
         hostname: raspberrypi.home
       username: root
       password: 88972207Tb!
       validate_certs: no
       guest: Debian_2
       state: powered_on
       vm_extra_config:
         vcpu.hotadd: yes
         mem.hotadd:  yes
       vm_disk:
         disk1:
           size_gb: 5
           type: thin
           datastore: Datastore_1
       vm_nic:
         nic1:
           type: vmxnet3
           network: VM Network
           network_type: standard
       vm_hardware:
         memory_mb: 512
         num_cpus: 1
         osid: DebianGuest
         scsi: paravirtual
         vm_cdrom:
           type: "iso"
           iso_path: "ISO_VM/debian-11.2.0-arm64-netinst.iso"
